apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysql-aycap-spring-ingress
spec:
  rules:
  - host: aycap-spring-mysql.gablekuber.180.222.156.218.xip.io
    http:
      paths:
      - backend:
          serviceName: aycap-spring-mysql
          servicePort: 8090
  - host: aycap-spring-91-mysql.gablekuber.180.222.156.218.xip.io
    http:
      paths:
      - backend:
          serviceName: aycap-spring-91-mysql
          servicePort: 8091
